const items = [
  {
    id: 1,
    title: "Chair",
    img: "chair.jpeg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "chair",
    price: 40,
  },
  {
    id: 2,
    title: "Chair",
    img: "chair2.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "chair",
    price: 45.5,
  },
  {
    id: 3,
    title: "Chair",
    img: "chair3.jpeg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "chair",
    price: 55.5,
  },
  {
    id: 4,
    title: "Chair",
    img: "chair4.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "chair",
    price: 120,
  },
  {
    id: 5,
    title: "Chair",
    img: "chair5.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "chair",
    price: 56,
  },
  {
    id: 6,
    title: "Sofa",
    img: "sofa1.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "sofa",
    price: 560,
  },
  {
    id: 7,
    title: "Sofa",
    img: "sofa2.webp",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "sofa",
    price: 820,
  },
  {
    id: 8,
    title: "Sofa",
    img: "sofa3.jpeg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "sofa",
    price: 500,
  },
  {
    id: 9,
    title: "Bed",
    img: "bed1.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "bed",
    price: 1000,
  },
  {
    id: 10,
    title: "Bed",
    img: "bed2.jpeg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "bed",
    price: 1700,
  },
  {
    id: 11,
    title: "Bed",
    img: "bed3.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "bed",
    price: 1285,
  },
  {
    id: 12,
    title: "Bed",
    img: "bed4.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "bed",
    price: 1450,
  },
  {
    id: 13,
    title: "Kitchen",
    img: "kitchen1.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "kitchen",
    price: 3200,
  },
  {
    id: 14,
    title: "Kitchen",
    img: "kitchen2.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "kitchen",
    price: 2500,
  },
  {
    id: 15,
    title: "Kitchen",
    img: "kitchen3.webp",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "kitchen",
    price: 1950,
  },
  {
    id: 16,
    title: "Kitchen",
    img: "kitchen4.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "kitchen",
    price: 2800,
  },
  {
    id: 17,
    title: "Bathroom",
    img: "bath1.jpeg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "bathroom",
    price: 1975,
  },
  {
    id: 18,
    title: "Bathroom",
    img: "bath2.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "bathroom",
    price: 1200,
  },
  {
    id: 19,
    title: "Bathroom",
    img: "bath3.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "bathroom",
    price: 1700,
  },
  {
    id: 20,
    title: "Table",
    img: "table1.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "table",
    price: 650,
  },
  {
    id: 21,
    title: "Table",
    img: "table2.png",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "table",
    price: 400,
  },
  {
    id: 22,
    title: "Light",
    img: "light1.jpg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "decor",
    price: 150,
  },
  {
    id: 23,
    title: "Light",
    img: "light2.jpeg",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "decor",
    price: 350,
  },
  {
    id: 24,
    title: "Mirror",
    img: "mirror1.png",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "decor",
    price: 85.3,
  },
  {
    id: 25,
    title: "Mirror",
    img: "mirror2.webp",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "decor",
    price: 100,
  },
];
export const categories = [
  { id: "001", category: "chair", name: "Chairs" },
  { id: "002", category: "sofa", name: "Sofa" },
  { id: "003", category: "table", name: "Tabels" },
  { id: "004", category: "bed", name: "Bedroom" },
  { id: "005", category: "kitchen", name: "Kitchen" },
  { id: "006", category: "bathroom", name: "Bathroom" },
  { id: "007", category: "decor", name: "Decors" },
];

export default items;
